version: '3.7'

services:
  database_Service:
    image: postgres:13-alpine
    restart: on-failure
    env_file: .env
    container_name: database_Service
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=pizzaManDb
    ports:
      - "5432:5432"
    volumes:
       - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
